#!/usr/bin/env python3
"""Bundle chapters/*.md into assets/chapters-data.js so index.html works from file://.

Run this after editing or adding any chapter:

    python3 build.py
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent
CHAPTERS_DIR = ROOT / "chapters"
OUT = ROOT / "assets" / "chapters-data.js"


def title_of(md: str, fallback: str) -> str:
    for line in md.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def main() -> int:
    files = sorted(CHAPTERS_DIR.glob("*.md"))
    if not files:
        print(f"No markdown files found in {CHAPTERS_DIR}", file=sys.stderr)
        return 1

    chapters = []
    for path in files:
        md = path.read_text(encoding="utf-8")
        raw_title = title_of(md, path.stem)
        # "12. Memory Management" -> number "12", title "Memory Management"
        m = re.match(r"^(\d+)\.\s*(.+)$", raw_title)
        number, title = (m.group(1), m.group(2)) if m else ("", raw_title)
        chapters.append(
            {
                "id": path.stem,
                "file": f"chapters/{path.name}",
                "number": number,
                "title": title,
                "words": len(md.split()),
                "markdown": md,
            }
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(chapters, ensure_ascii=False, indent=None)
    OUT.write_text(
        "/* Generated by build.py - do not edit by hand. */\n"
        "window.CHAPTERS_DATA = " + payload + ";\n",
        encoding="utf-8",
    )

    total_words = sum(c["words"] for c in chapters)
    size_kb = OUT.stat().st_size / 1024
    print(f"Wrote {OUT.relative_to(ROOT)}  ({len(chapters)} chapters, "
          f"{total_words:,} words, {size_kb:,.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
